"""Routing Provider ABC and Result Dataclasses for OVON Core."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone

from packages.ovon_core.domain import Coordinate, LoopRequest, RoutePersona


@dataclass(frozen=True, slots=True)
class RoutingProvenance:
    """Provenance and metadata for a routing graph calculation."""

    provider_name: str = "OSMnx + igraph"
    graph_version: str = "OSM Pedestrian Walk Network"
    nodes_count: int = 0
    edges_count: int = 0
    calculated_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc), compare=False
    )


@dataclass(frozen=True, slots=True)
class LoopRouteCandidate:
    """Calculated closed loop candidate generated by a routing provider."""

    persona: RoutePersona
    name: str
    tagline: str
    duration_minutes: int
    distance_meters: float
    badge_label: str
    tradeoff_description: str
    geojson_geometry: dict
    waypoints: tuple[Coordinate, ...]
    segment_metrics: tuple[dict, ...] = ()


@dataclass(frozen=True, slots=True)
class RoutingResult:
    """Complete result package returned by a RoutingProvider."""

    origin: Coordinate
    duration_minutes: int
    candidates: tuple[LoopRouteCandidate, ...]
    provenance: RoutingProvenance


class RoutingProvider(ABC):
    """Abstract Base Class interface for OVON spatial loop routing solvers."""

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Name of the routing provider implementation."""
        pass

    @abstractmethod
    def calculate_loop(self, request: LoopRequest) -> RoutingResult:
        """Calculate closed walking loop candidates matching the LoopRequest."""
        pass
